services:
  nginx:
    image: nginx:latest
    container_name: pify-player-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/player.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
    networks:
      - pify-player-dev-network

  frontend:
    build:
      context: ./player
      dockerfile: dev.Dockerfile
    container_name: pify-player-frontend
    ports:
      - "5173:5173"
      - "24678:24678"
    volumes:
      - ./player:/app
      # following lines needed to allow container to persist own folder, rather than allowing local to override
      - /app/.svelte-kit
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - pify-player-dev-network

  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    container_name: pify-player-api
    volumes:
      - ./api:/app
    environment:
      - PORT=5000
    networks:
      - pify-player-dev-network

networks:
  pify-player-dev-network:
    driver: bridge
