services:
  frontend:
    build:
      context: ./player
      dockerfile: Dockerfile
    container_name: pify-player-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - .env
    networks:
      - pify-player-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pify-player-api
    ports:
      - "8080:443"
    volumes:
      - ./api/database:/app/database
    env_file:
      - .env
    networks:
      - pify-player-network

networks:
  pify-player-network:
    driver: bridge
