services:
  nginx:
    image: nginx:latest
    container_name: pify-player-nginx
    ports:
      - "8080:80"
    volumes:
      - ./player/build:/usr/share/nginx/html
      - ./nginx/player.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
    networks:
      - pify-player-network

  frontend:
    build:
      context: ./player
      dockerfile: Dockerfile
    container_name: pify-player-frontend
    environment:
      - PORT=3000
    networks:
      - pify-player-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pify-player-api
    environment:
      - PORT=5000
    networks:
      - pify-player-network

networks:
  pify-player-network:
    driver: bridge
