services:
  frontend:
    build:
      context: ./player
      dockerfile: dev.Dockerfile
    container_name: pify-player-frontend
    ports:
      - "5173:5173"
      - "24678:24678"
    volumes:
      - ./player:/app
      - ./certs:/app/certs
      # following lines needed to allow container to persist own folder, rather than allowing local to override
      - /app/.svelte-kit
      - /app/node_modules
    depends_on:
      - api
    environment:
      - NODE_ENV=development
    networks:
      - pify-player-dev-network

  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    container_name: pify-player-api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - ./certs:/app/certs
    environment:
      - PORT=8080
      - CORS_ORIGINS=huijie-mbp.local
      - SSL_DOMAIN=huijie-mbp.local
    networks:
      - pify-player-dev-network

networks:
  pify-player-dev-network:
    driver: bridge
