services:
  nginx:
    image: nginx:latest
    container_name: pify-player-nginx
    ports:
      - "5173:5173"
    volumes:
      - ./player/nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/private
    depends_on:
      - frontend
      - api
    networks:
      - pify-player-network
  frontend:
    build:
      context: ./player
      dockerfile: Dockerfile
      args:
        - NODE_ENV
        - VITE_CERT_PATH
        - VITE_ALLOWED_SERVERS
        - VITE_DOMAIN
        - PLAYER_NAME
        - BASIC_AUTH_USERNAME
        - BASIC_AUTH_PASSWORD
        - ENABLE_YOUTUBE
        - YOUTUBE_API_KEY
    container_name: pify-player-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - .env
    networks:
      - pify-player-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pify-player-api
    ports:
      - "8080:443"
    privileged: true
    volumes:
      - ./api/database:/app/database
      - /sbin:/host_sbin:ro
    env_file:
      - .env
    networks:
      - pify-player-network

networks:
  pify-player-network:
    driver: bridge
