services:
  frontend:
    build:
      context: ./player
      dockerfile: dev.Dockerfile
    container_name: pify-player-frontend
    ports:
      - "5173:5173"
      - "24678:24678"
    volumes:
      - ./player:/app
      # following lines needed to allow container to persist own folder, rather than allowing local to override
      - /app/.svelte-kit
      - /app/node_modules
    depends_on:
      - api
    env_file:
      - .env
    networks:
      - pify-player-dev-network

  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    container_name: pify-player-api
    ports:
      - "8080:443"
    volumes:
      - ./api:/app
      - ./api/database:/app/database
    env_file:
      - .env
    networks:
      - pify-player-dev-network

networks:
  pify-player-dev-network:
    driver: bridge
