services:
  frontend:
    build:
      context: ./player
      dockerfile: Dockerfile
    container_name: pify-player-frontend
    volumes:
      - ./certs:/app/certs
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - pify-player-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pify-player-api
    ports:
      - "8080:8080"
    volumes:
      - ./certs:/app/certs
    environment:
      - PORT=8080
      - CORS_ORIGINS=huijie-mbp.local
      - SSL_DOMAIN=huijie-mbp.local
    networks:
      - pify-player-network

networks:
  pify-player-network:
    driver: bridge
