FROM node:22

WORKDIR /app

# Declare build arguments
ARG PORT
ARG VITE_CERT_PATH
ARG VITE_ALLOWED_SERVERS
ARG VITE_DOMAIN
ARG PLAYER_NAME
ARG BASIC_AUTH_USERNAME
ARG BASIC_AUTH_PASSWORD
ARG ENABLE_YOUTUBE
ARG YOUTUBE_API_KEY

# Set environment variables from build arguments
ENV NODE_ENV=development
ENV PORT=${PORT}
ENV VITE_CERT_PATH=${VITE_CERT_PATH}
ENV VITE_ALLOWED_SERVERS=${VITE_ALLOWED_SERVERS}
ENV VITE_DOMAIN=${VITE_DOMAIN}
ENV PLAYER_NAME=${PLAYER_NAME}
ENV BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
ENV BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
ENV ENABLE_YOUTUBE=${ENABLE_YOUTUBE}
ENV YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

COPY . .
RUN npm install

EXPOSE 5173
EXPOSE 24678

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]